### ISSUE TITLE
How to restart openshift-ansible step: OS::Heat::SoftwareDeployment?

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#123]
My install failed on the docker downgrade issue.  I worked around it on the nodes, and I'll wait for the errata package release from Red Hat to allow the downgrade or swap.

However, I'd like to not have to rebuild everything.  

How can I trigger heat (or ansible) to restart and finish the heat stack-create?

Let's add the answer to the debugging doc. #121

**Comment by jprovaznik** [comment]
run the exactly same command as when creating the stack, but instead of "heat stack-create ..." use "heat stack-update ...". I haven't tied this for a long time on create_failed state, but in general it should work. It's good idea to add a note about this into the debugging doc once we know it works - let me know please how it works.

**Comment by juddmaltin-dell** [comment]
It's working OK:

```
heat   \
   stack-update openshift \
   -t 120 \
   -e openshift_parameters.yaml \
   -f ~/openshift-on-openstack/openshift.yaml
```
