### ISSUE TITLE
DNS names are wrong.  Prefixed in dnsmasq, not prefixed in heat output

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#128]
Heat output after successful heat create run shows:

```
[osp_admin@director openshift-on-openstack]$ heat output-show openshift console_url
"https://lb.example.com:8443/console/"
```

Query for lb.example.com

```
[osp_admin@director openshift-on-openstack]$ dig @192.168.191.16 lb.example.com

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @192.168.191.16 lb.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 10307
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;lb.example.com.                        IN      A

;; Query time: 1 msec
;; SERVER: 192.168.191.16#53(192.168.191.16)
;; WHEN: Wed May 25 15:01:25 EDT 2016
;; MSG SIZE  rcvd: 32
```

Query for openshift-lb.example.com:

```
osp_admin@director openshift-on-openstack]$ dig @192.168.191.16 openshift-lb.example.com

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @192.168.191.16 openshift-lb.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35571
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;openshift-lb.example.com.      IN      A

;; ANSWER SECTION:
openshift-lb.example.com. 0     IN      A       192.168.191.14

;; Query time: 1 msec
;; SERVER: 192.168.191.16#53(192.168.191.16)
;; WHEN: Wed May 25 14:56:46 EDT 2016
;; MSG SIZE  rcvd: 58

```

/etc/hosts  on infra

```
[root@openshift-infra log]# cat /etc/hosts
#
# Initialize the hosts file for dnsmasq on the infra host
#
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

192.168.191.16 openshift-infra.example.com openshift-infra
192.168.191.14 openshift-lb openshift-lb.example.com
192.168.191.18 openshift-openshift-master-1.example.com openshift-openshift-master-1 #openshift
192.168.191.19 openshift-openshift-master-0.example.com openshift-openshift-master-0 #openshift
192.168.191.20 openshift-openshift-master-2.example.com openshift-openshift-master-2 #openshift
192.168.191.21 openshift-openshift-node-7c6s2h1s.example.com openshift-openshift-node-7c6s2h1s #openshift
192.168.191.22 openshift-openshift-node-18l6k9j7.example.com openshift-openshift-node-18l6k9j7 #openshift
192.168.191.23 openshift-openshift-node-4vf83ga6.example.com openshift-openshift-node-4vf83ga6 #openshift
192.168.191.24 openshift-openshift-node-k1c231l3.example.com openshift-openshift-node-k1c231l3 #openshift
```

**Comment by jprovaznik** [comment]
Hi Judd,
openshift-lb.example.com is an "entry point" for users/world when talking to openshift console/api. So DNS record of openshift-lb.example.com needs to be set on DNS server you use (or in your /etc/hosts), we do not (and can not) do this automatically I'm afraid.

**Comment by juddmaltin-dell** [comment]
Hi Jan,

Let me know if I have this straight: the lb.example.com name is for setting on whatever external DNS that world is talking to, while openshift-lb.example.com is for DNS internal to OpenShift.

Secondly, if I seek integration with an IaaS service such as OpenStack would that require yet another DNS host or domain?  Are there docs for this?

Thanks so much, I'm overjoyed to have the deployment working!  Summit is going to be great!
-Judd

**Comment by jprovaznik** [comment]
Reopening this. I misread your output yesterday - yes, this is a bug: there should be "openshift-lb.example.com" everywhere (I sent a patch for this).

Anyway openshift-lb.example.com still has to be set on an external DNS if you want to access openshfit from outside. openshift-lb.example.com is for setting  on whatever external DNS that world is talking to, also this address is set on internal DNS being set for resolving openshift nodes, the reason is that openshift ndoes have this address set as public url so they need to resolve it (and we can't rely on fact that it will be set properly on an external DNS). BTW we are moving toward delegate DNS setup to openshift-ansible https://github.com/redhat-openstack/openshift-on-openstack/pull/119

Re: IaaS - (correct me if I misunderstood question) - I don't think any additional VM, domain would help, you just need a working DNS record for openshift entry point. Speaking particulary about OpenStack there is DNSaaS (Designate) which would be used for this situation.  We actually had a working POC which used designate-sink for automating DNS records setup for openshift nodes. Integration with Designate is on TODO list but not sure when we get to it (patches welcome), this integration will have to be optional. Good news is that there is designate support in heat resource types (http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Designate::Record). For making this optional I can imagine we could use same approach as with loadbalancers - in loadbalancer template we would create a OOshift::DNSRecord which would map either to a fake resource type or to real OS::Designate::Record.
