### ISSUE TITLE
No floating ip for openshift  nodes

### ISSUE THREAD

**Issue by alessiodini** [redhat-openstack/openshift-on-openstack#163]
Hello all,
if you read the description of the project you can read:

"Every VM in this configuration is also given a floating IP address on the public network. This provides direct access to the master and node hosts when needed."

When I deploy multiple nodes I see that the master and infra vm only are getting floating ip from Openstack. 
When I create the Openshift router , this is scheduled and created on one of the available nodes but at same time these nodes are not reachable from the external network because they don't have floating ip. How am I supposed to reach exposed services pointing the floating ip of the master node when the router is deployed on other nodes?
Can someone help me? I'm a bit confused

i attach a couple of screenshots from my Horizon:
Openshift Master and Infra hosts
![master and infra](https://cloud.githubusercontent.com/assets/20000376/16340068/5c4bf59c-3a26-11e6-88af-2172e3ee51e6.PNG)

Openshift nodes
![nodes](https://cloud.githubusercontent.com/assets/20000376/16340083/71dc46b4-3a26-11e6-93ab-fc79e1e3d333.PNG)

**Comment by lebauce** [comment]
Thanks for reporting this. The behaviour changed recently and only the master nodes have a floating IP (we'll update the doc shortly).

A router should be automatically created during the stack creation. A selector "region=infra" is specified so that the router is deployed on the master nodes only.

If you deploy a router manually, please make sure the master nodes are marked as 'schedulable' (oadm manage-node hostname --schedulable) and to use the "region=infra" selector.

**Comment by alessiodini** [comment]
Thank you for your time , I try it!
Regards

**Comment by lebauce** [comment]
@adini83 Can we close this issue ?

**Comment by alessiodini** [comment]
@lebauce  sorry for this late reply,
I can not tell you because I changed to the enterprise version!
Thank you for your time
