### ISSUE TITLE
HA install fails - deploying on packstack --allinone

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#47]
Is it a complete anti-pattern to install OpenShift HA like this on a single hardware node running Packstack --allinone with heat, etc?  If most everything is contained in different VMs, wouldn't it work?  Thanks!

heat stack-create my_openshift --poll -t 180 \
  -e openshift_parameters.yaml \
  -e openshift-on-openstack/env_ha.yaml \
  -f openshift-on-openstack/openshift.yaml

20:01:5  2016-02-24  0f732d51-9bef-4512-bb6b-17701ce885c1 [lb_host]: CREATE_FAILED  Conflict: resources.lb_host.resources.host: Port
ea66dec1-2c40-48ae-84d9-95c6ff681ccb is still in use. (HTTP 409) (Request-ID: req-2981aa4f-3e2e-4cee-8260-3df28be386f3)
20:01:5  2016-02-24  0661636a-3885-42fe-a15e-22fe7e185dfa [my_openshift]: CREATE_FAILED  Resource CREATE failed: Conflict: resources. 
lb_host.resources.host: Port ea66dec1-2c40-48ae-84d9-95c6ff681ccb is still in use. (HTTP 409) (Request-ID: req-2981aa4f-3e2e-4cee-826
0-3df28be386f3)

Port Details

Name
    my_openshift-lb_host-w5ty7wsehank-port-bv5bpxr4yp34
ID
    ea66dec1-2c40-48ae-84d9-95c6ff681ccb
Network ID
    575dff93-bc92-433a-864a-d292b475b75d
Project ID
    00116efdc59f44f6954eeae263b36821
MAC Address
    fa:16:3e:ae:e7:bf
Status
    Active
Admin State
    UP
Fixed IP
    None
Attached Device
Device Owner
    compute:None
Device ID
    17b7c98e-251e-44fe-9b40-19fa83d02990
Binding
Host
    hw1.openshift.oss.lab
Profile
    None
VIF Type
    ovs
VIF Details

```
    port_filter True
    ovs_hybrid_plug True
```

VNIC Type
    normal

**Comment by scollier** [comment]
@markllama @jprovaznik Any thoughts here?

**Comment by jprovaznik** [comment]
You can use all-in-one single node openstack deployments (actually I use this for development) but make sure you set heat parameter "master_server_group_policies: affinity", otherwise master instances will end in error state. But it seems this one is a different error. I wonder if it's because lb host resource fails to create and was re-created -> that would explain why the lb host port is being used, anything interesting in nova scheduler logs? Also maybe "heat event-list -n 3 my_openshift" might help.

One important note - today we merged a commit which removes dedicated loadbalancer host, instead neutron's LBaaS service is used so if you have neutron LBaaS enabled you might give it a shot.

**Comment by juddmaltin-dell** [comment]
It turns out my packstack storage was in an error state thanks to a known bug.

Adding docs to readme to ensure that --os-neutron-lbaas-install=OS_NEUTRON_LBAAS_INSTALL is set to "yes."
